### PR TITLE
LPS-108231 Set restart-required to false for CCR

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-108231

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
Nothing to test, not triggering actual test suites.

**Comment by lipusz** [comment]
My bad, I forgot that Similar Results will be bundled with 7.3, so that commit is needed for 7.2.x only. Removing

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
Oh boi...

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Comment by lipusz** [comment]
When an easy task becomes ... being not easy. 🤕

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Comment by lipusz** [comment]
Hey @BryanEngler 

:heavy_check_mark: The SF error is expected: it happened on the previous PRs too where we set this property to false, we just need to tell Brian that we are confirming it's safe to set to false when sending to him. :+1:

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84344

**Pull request closed without merging**
