### PR TITLE
2019_03_01_LPS_87972_search_engine_info Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
> ### ❌ ci:test:search-solr - 13 out of 18 jobs passed in 2 hours 34 seconds 985 ms
> Click here for more details.

## ANALYSIS
### Jenkins Report
https://test-1-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4133/jenkins-report.html
### Failed Tests
* functional-tomcat90-mysql57-jdk8: Solr#SolrWithSolrCloudSmokeTest fixed by [LPS-87410](https://issues.liferay.com/browse/LPS-87410)
* js-unit-jdk8: js-unit-jdk8 tests failing due to FragmentsEditorIdUtils & portal-workflow-metrics-web
### Unstable Tests
* functional-tomcat90-mysql57-jdk8: Same error happened on canary. Unrelated test failure.
* modules-integration-mysql57-jdk8: Multiple testIndexedFields across different components failing. ConfigurationModelIndexerTest.testSearchAfterReindex.

**Comment by xbrianlee** [comment]
> ### ❌ ci:test:search - 14 out of 17 jobs passed in 1 hour 25 minutes 24 seconds 743 ms
> Click here for more details.

## ANALYSIS
### Jenkins Report
https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3743/jenkins-report.html
### Failed Tests
* js-unit-jdk8: failure on dynamic-data-mapping-form-builder
### Unstable Tests
* functional-tomcat90-mysql57-jdk8: Seems to be a fluke. Fails to click ellipsis and then 'move to recycle bin'.

**Comment by BryanEngler** [comment]
ci:test:sf

**Pull request closed without merging**
