### PR TITLE
LPS-92816 Remove 'Synchronized Search' setting which has no impact on Embedded connection since Elasticsearch 6

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-92816

:heavy_check_mark: `ci:test:sf` passed here: https://github.com/lipusz/liferay-portal/pull/259#issuecomment-477175995
:heavy_check_mark: `ci:test:search` passed with no unique failures here: https://github.com/lipusz/liferay-portal/pull/259#issuecomment-477249613

Used commit from http://search-ci.liferay.com/ as base.

Regards,
Tibi

### CODE REVIEW

**Comment by lipusz** [comment]
Also removing the lang keys, pushing in a few minutes.

**Comment by lipusz** [comment]
I can send it to Brian if you're okay. Thanks!

**Comment by BryanEngler** [comment]
ya looks good to me, go ahead and send

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/70837

**Pull request closed without merging**
