### PR TITLE
LPS-90078 Search Results widget "Pagination Delta" should default to search.container.page.default.delta

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-90078

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
running `ci:test:search` here https://github.com/BryanEngler/liferay-portal/pull/309#issuecomment-460876393 and then i will send to bchan

**Pull request closed without merging**
