### PR TITLE
LPS-166987 | LPS-167293, LPS-168594, LPS-169469 Capabilities API

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:help

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:test:workflow-metrics

**Comment by xbrianlee** [comment]
ci:test:search:e56aff76be7cb4dbdebbb3eb2730fb199918ac2c

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:workflow-metrics

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:test:bundle

**Comment by BryanEngler** [comment]
ci:test:search:e56aff76be7cb4dbdebbb3eb2730fb199918ac2c

**Comment by xbrianlee** [comment]
ci:test:commerce

Running the test suites above because I believe many of them ran into https://issues.liferay.com/browse/LPS-169973

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:workflow-metrics

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by suilin** [comment]
@xbrianlee, I finished the analysis for Search, Relevant and Commerce suites, all of the failures are not related to current changes. Could you help to look at workflow suite? Thank you!

**Comment by BryanEngler** [comment]
sent a pr to commerce for their review - https://github.com/liferay-commerce/liferay-portal/pull/3232

**Comment by BryanEngler** [comment]
sent a pr to workflow for their review - https://github.com/liferay-workflow/liferay-portal/pull/860

i let them know we were still analyzing the workflow suite results

**Comment by xbrianlee** [comment]
Results from `workflow-metrics` suite are good. I left a comment on the PR: https://github.com/liferay-workflow/liferay-portal/pull/860.

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:commerce

**Comment by BryanEngler** [comment]
ci:help

**Comment by BryanEngler** [comment]
ci:test:workflow-metrics

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:close

Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/127697

**Pull request closed without merging**
