### PR TITLE
LPS-132030

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
hey @BryanEngler when I ran the tests for your pull (with my cosmetic changes), I got this:

```
Caused by: java.lang.IllegalArgumentException: Name must not contain .: nestedFieldArray.fieldName
	at com.liferay.portal.kernel.search.Field.validate(Field.java:539) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.search.Field.<init>(Field.java:313) ~[portal-kernel.jar:?]
	at com.liferay.portal.search.elasticsearch7.internal.SearchHitDocumentTranslatorImpl.translate(SearchHitDocumentTranslatorImpl.java:89) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.SearchHitDocumentTranslatorImpl.getField(SearchHitDocumentTranslatorImpl.java:80) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.SearchHitDocumentTranslatorImpl.addField(SearchHitDocumentTranslatorImpl.java:56) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.SearchHitDocumentTranslatorImpl.translate(SearchHitDocumentTranslatorImpl.java:46) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.response.DefaultSearchResponseTranslator.processSearchHit(DefaultSearchResponseTranslator.java:192) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.response.DefaultSearchResponseTranslator.processSearchHits(DefaultSearchResponseTranslator.java:212) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.response.DefaultSearchResponseTranslator.populate(DefaultSearchResponseTranslator.java:100) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchSearchResponseAssemblerImpl.assemble(SearchSearchResponseAssemblerImpl.java:81) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchSearchRequestExecutorImpl.execute(SearchSearchRequestExecutorImpl.java:71) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.ElasticsearchSearchRequestExecutor.executeSearchRequest(ElasticsearchSearchRequestExecutor.java:59) ~[bundleFile:?]
	at com.liferay.portal.search.engine.adapter.search.SearchSearchRequest.accept(SearchSearchRequest.java:45) ~[bundleFile:?]
	at com.liferay.portal.search.engine.adapter.search.SearchSearchRequest.accept(SearchSearchRequest.java:34) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:103) ~[bundleFile:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexSearcher.search(ElasticsearchIndexSearcher.java:127) ~[bundleFile:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.messaging.proxy.ProxyReq
```

Can you fix it and send it back to me? Thanks.

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
the reason you are getting that error is because you need to do a full reindex to apply the new mappings that we are adding https://github.com/BryanEngler/liferay-portal/pull/582/commits/122d38a4fea473711baf611d1b4b2bf0b183b5d0

i am adding one more commit to this branch, will run tests/forward from here https://github.com/BryanEngler/liferay-portal/pull/583

**Pull request closed without merging**
