### PR TITLE
LPS-65342

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-65342

I just used all the changes you made, but rebased my first commit from this: https://github.com/BryanEngler/liferay-portal/pull/163/commits/9aed3f350912e3f795dae37e7704a8ded517e462#diff-71e719e586300333a4fe871d75de78f7R40

to this: https://github.com/BryanEngler/liferay-portal/commit/2bf7e71a398b8ba7c6b2cda6483caa14ccf31d49#diff-71e719e586300333a4fe871d75de78f7R39

### CODE REVIEW

**Comment by BryanEngler** [comment]
@juliocamarero Quick question - Did you want us to put the Role related logic in a DataHandler as well or is this ok - b568280bd8bc866e5659b6cfdba206331b675e75?

**Comment by juliocamarero** [comment]
Hey @BryanEngler 

it's the same problem... but here we can't use the other approach. 

What we do in other places of the portal is to use a ModelListener (such as GroupModelListener in journal-service).

I've been looking at the code with @sergiogonzalez (who will review your pull) and maybe it's better if you do ModelListeners when your entities don't support staging.

After looking at the code we think that:
- If your entity supports staging and the option to delete data before importing, then the logic to delete your entity should be in a portlet data handler.
- Otherwise, just use a ModelListener to do something after an entity (Role, Group) has been deleted.

thanks a lot!

**Comment by ChrisKian** [comment]
I've added changes based off Julio's comment.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/982

**Pull request closed without merging**
