### PR TITLE
[Whitehat] LPS-102883 Bump org.bouncycastle libs to 1.61 for ES6 and ES7

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-102883

Hey Bryan,

Please see the details on the ticket.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:help

**Comment by lipusz** [comment]
@xbrianlee How can we trigger running the test with ES6?

**Comment by xbrianlee** [comment]
The functional failures in the `ci:test:search` run above are unrelated to the changes in this PR

**Comment by xbrianlee** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/80982

**Pull request closed without merging**
