### PR TITLE
pr_2020_02_05_pr472_LPS_107382_null_searchhits Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
Thanks for continuing work on this Bryan

**Comment by joshuacords** [comment]
Rebasing onto the next stable hash should remove the Conflicting files problem.

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84291

**Pull request closed without merging**
