### PR TITLE
LPS-61008

### PR DESCRIPTION
**Pull request by mbowerman**
Added updated ServiceBuilder files to cache, hopefully this causes it to pass the tests

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hey @BryanEngler,

We're going to leave this pull request open for now. The reason it's failing is because the updated version of Service Builder needs to be put on the CDN first. I sent a pull request to @dustinryerson that included just my changes to the Service Builder. Once that goes through, and Brian Chan puts it up on the CDN, we can retest this, and the tests should pass.

**Comment by BryanEngler** [comment]
ill go ahead and close this since im going to be on pto all next week. if the other pr gets committed you can send this pr to mccann

**Pull request closed without merging**
