### PR TITLE
LPS-68085

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-68085

Ok, I think this should do it now.  It compiled and ran fine on my local machine.

https://github.com/BryanEngler/liferay-portal/pull/187

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
this looks fine, im cleaning up my repos right now so i cant send mccann a pr but ill go ahead and close this if you want to send it to him

**Comment by ChrisKian** [comment]
Done, see https://github.com/jonathanmccann/liferay-portal/pull/1061

**Pull request closed without merging**
