### PR TITLE
LPS-95707 portal-search-web: Properly display value

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-95707

Decided to keep the inputs visible since hiding them for the admin made the portlet more difficult to configure. For `invisible` enabled the input will still be editable, but for `immutability` enabled the input will be disabled.

This also fixes the input value from using the value from the URL when the "immutability" setting is enabled.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/369

**Pull request closed without merging**
