### PR TITLE
LPS-112251

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:forward

**Comment by lipusz** [comment]
Thanks for catching it, @BryanEngler . :+1:

**Comment by lipusz** [comment]
Hey @BryanEngler 

After some struggles with the ElasticsearchConnectionConfigurations, I was able test it on master with a remote 7.6.0.

Here are my steps & configs: Configure your remote ES as it's written on the ticket, then
1. Build `elasticsearch7` from this branch
2. Edit `osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConnectionConfiguration-default.config` and the following content:
```config
active=B"true"
authenticationEnabled=B"false"
connectionId="remote"
httpSSLEnabled=B"true"
networkHostAddresses=["https://localhost:9200"]
truststorePassword="liferay"
truststorePath="/path/to/certs/elastic-certificates.p12"
truststoreType="pkcs12"
```
Update the path to match with your env.
4. Create `com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config` with the following content:
```config
operationMode="REMOTE"
remoteClusterConnectionId="remote"
```
5. Generate PKCS#12 format certificate for your ES node:
```bash
./bin/elasticsearch-certutil cert --ca-cert config/certs/ca.crt --ca-pass liferay --name "CN=liferay.com,OU=Services,DC=liferay,DC=com" --dns localhost --ca-key config/certs/ca.key
```
6. Copy the generated file as `elastic-certificates.p12` to `ES_HOME/config/certs`
7. Start ES
8. Start portal

master-es7-remote-PKI

Good to go. :+1:

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
