### PR TITLE
LPS-88736 portal-search-test: adding integration test for log info in index searcher

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
hey wade, i think the original behavior logged the messages for calls to `searchCount()` as well. can you verify that, and then write a test for `searchCount()` and add the logging back to `searchCount()` too.

and i think andre also wanted the same logging in `CountSearchRequestExecutorImpl`, `MultisearchSearchRequestExecutorImpl`, and `SearchSearchRequestExecutorImpl`

thanks!

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
reviewed and sent to bchan https://github.com/brianchandotcom/liferay-portal/pull/66441

**Pull request closed without merging**
