### PR TITLE
LPS-57484

### PR DESCRIPTION
**Pull request by ssmith353**
On the live site, we need to change the permissions so they admins can view the scheduled content; even though it won't be viewable to the regular users. 

Currently, if it's in the scheduled state, and on the live site, they will not have UPDATE permission, by design, automatically returning "false" for view permission. 

Web content doesn't work this way for scheduled content on the live site, and LPS-41902 was reverted in JournalArticlePermssion.java. 

If I remove LPS-41902, it becomes reproducible again. I wasn't sure if there was a better way to check for the unique permissions case; of scheduled blogs, and remote staging. 

https://github.com/sergiogonzalez/liferay-portal/pull/2482

### CODE REVIEW

**Comment by BryanEngler** [comment]
this doesnt seem like its the most complete way to fix this... what if the user isnt the owner but maybe just a site administrator? a site administrator should be able to see a scheduled entry regardless of the owner right?

**Comment by ssmith353** [comment]
I think this will work better, if the site admins are given permission they can view - and this still protects against LPS-41902.

**Comment by BryanEngler** [comment]
this new one still checks for the 'update' permission but you say live wont have the update permission so wouldnt this still return false?

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/870

**Pull request closed without merging**
