### PR TITLE
LPS-114395 Update replicas/shards lang key

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
this is gonna end up conflicting with https://github.com/BryanEngler/liferay-portal/pull/505 so im gonna wait for that pr to be merged before sending this one

**Comment by joshuacords** [comment]
Hi @BryanEngler, #505 has been merged

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
