### PR TITLE
LPS-95940 Clicking the tag on a search result doesnt add filter after changing parameter name in facet config

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-95940

Hello @BryanEngler,
This is my current solution for LPS-95940. You can see I use the searchContext to pass along the parameters needed for tags and categories so that they dynamically change with those portlets.

There is a potential issue however, if 2 tag or category portlets with different parameter names are on the Search Results page, then the name used will be inconsistently between the 2 portlet parameter names. This use case doesn't make much sense to me, so I'm not too worried. If we wanted to try to address this by adding ALL available parameter names of tag and category portlets, we would need to change the [SearchResultSummaryDisplayContext](https://github.com/liferay/liferay-portal/blob/a46e31640b7a2a1f32a4616253916399d5421b91/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/result/display/context/SearchResultSummaryDisplayContext.java#L233-L235) structure as well as the [jsp](https://github.com/liferay/liferay-portal/blob/722f4eeea131fd7ea77a81d63219b5a35b979a65/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/search/results/view.jsp#L179-L191). Let me know if you want that done.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey @joshuacords 

is this still needed? Can you please check if it still affects master and if so, rebase and update this PR?

Thanks!

**Comment by joshuacords** [comment]
Hi @lipusz,

I'll double check on this. Progress halted as a test for this behavior was requested, but at the time I didn't have bandwidth to find how to create the needed test.

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
This is still an issue in master, I've rebased and am retesting.

**Comment by joshuacords** [comment]
I understand @BryanEngler wants a test for this, but it's a bit unclear to me how to create such a test and I will need some guidance there.

**Comment by joshuacords** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
I mixed it with another PR from the metrics list so I though it was poisoning our metrics unnecessarily. Checked that it does not. ;-) :taco:

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
