### PR TITLE
2021_09_22_LPS_139636_sidecar_checksum_nexus

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-remote

**Comment by BryanEngler** [comment]
ci:test:search-remote-minimum

**Comment by BryanEngler** [comment]
@lipusz this pr has an additional commit on top of the branch being tested in https://github.com/BryanEngler/liferay-portal/pull/621 
the additional commit downloads the elastic artifacts from our nexus since you mentioned we should consider it on https://issues.liferay.com/browse/LPS-139636 
but im not sure if the artifacts should be on nexus or some other mirrors? do you know?

**Comment by lipusz** [comment]
> @lipusz this pr has an additional commit on top of the branch being tested in #621
> the additional commit downloads the elastic artifacts from our nexus since you mentioned we should consider it on https://issues.liferay.com/browse/LPS-139636
> but im not sure if the artifacts should be on nexus or some other mirrors? do you know?

Hmm, I think we should be using the CDN URL: `https://repository-cdn.liferay.com/nexus/...`. At least, this is what the `build.properties` is also referencing. But it might be worth checking with the IT. :thinking: Can you do that?

**Comment by lipusz** [comment]
As I can see the hosted version is only 72MB, while if download the 7.10.2 OSS no-jdk version from Elastic it is ~156MB. Is this because you have already removed the unnecessary parts from the self-hosted archive? If so, :+1: !

**Pull request closed without merging**
