### PR TITLE
LPS-57484

### PR DESCRIPTION
**Pull request by ssmith353**
So the second permission one is just like the revert done for JournalArticle: https://github.com/liferay/liferay-portal/commit/71baa2a7473ff0100730e0e1d938d60760f2b1d8

LPS-41902 is no longer reproducible.

### CODE REVIEW

**Comment by ssmith353** [comment]
ci:retest

**Comment by ssmith353** [comment]
ci:retest

**Comment by ssmith353** [comment]
ci:retest

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/780

**Pull request closed without merging**
