### PR TITLE
LPS-62876

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by BryanEngler** [comment]
does ParamUtil.getLong(actionRequest, "fileEntryId"); return a different value than fileEntry.getFileEntryId(); ?

**Comment by BryanEngler** [comment]
if its the same value then we shouldnt need these lines right?

```java
FileEntry fileEntry = _dlAppService.getFileEntry(fileEntryId);

long assetClassPK = fileEntry.getFileEntryId();
```

**Comment by mbowerman** [comment]
Yeah, it does return the same thing, so we can get rid of those two lines and use fileEntryId instead of assetClassPK. Good catch.

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/934

**Pull request closed without merging**
