### PR TITLE
LPS-155753 Search Bar Suggestions doesn't work with "Everything" scope

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@joshchong just wanted to confirm that we broke these two tests with these changes?
LocalFile.Search#SearchDifferentScopesViaNewSite
LocalFile.Search#ViewStagedAndLiveContentInSearchResults

if so, i guess we will have to figure out if the tests need to be updated or if we need to change the fix
cc @thektan

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by thektan** [comment]
@joshchong Thanks for catching this...looking into it now.

**Pull request closed without merging**
