### PR TITLE
LPS-87410 Properly close Solr clients

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-87410

Hi Bryan,

Tested by @xbrianlee too, see https://issues.liferay.com/browse/LPS-87410?focusedCommentId=1914493&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1914493.

Regarding my 2nd commit: despite the LPS was about SolrCloud I can't think of any reasons why we wouldn't want to close the clients of ReadWriteSolrClient though feel free to drop that commit if you think we don't need it.

Looking at the history looks like it was added initially like that by Mike for the Solr 5 connector.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search-solr

**Comment by lipusz** [comment]
Note: Solr#SolrWithSolrCloudSmokeTest is not completing properly by https://issues.liferay.com/browse/LRQA-50851:
```
/opt/dev/projects/github/liferay-portal/build-test-solr.xml:385: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:2560: /opt/dev/projects/github/liferay-portal/bundles/solr-7.5.0/server/logs/solr.log doesn't exist
```

**Comment by BryanEngler** [comment]
i know you didnt write this code, but what do you think about the `_log.warn("");`...?

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/76363

**Pull request closed without merging**
