### PR TITLE
LPS-157872_Modified_Date_Modified_User_Name_Modified_User_Portrait_and_Creator_User_Portrait_are_available_in_the_Search_Results_Widget_Template_Context

### PR DESCRIPTION
**Pull request by gustavolimav**

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
this would work, but see if you can get https://github.com/BryanEngler/liferay-portal/pull/667#issuecomment-1247357534 to work instead, thanks!

**Comment by brookedalton** [comment]
ci:stop

**Pull request closed without merging**
