### PR TITLE
[TS] LPS-109095 Elasticsearch bulk execution failures are not logged properly

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-109095](https://issues.liferay.com/browse/LPS-109095)

Hi Bryan,

I hope you can review my changes. Initial review was made here: https://github.com/lipusz/liferay-portal/pull/299

Thank you in advance,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf:norebase

**Comment by istvansajtos** [comment]
ci:test:relevant:norebase

**Comment by istvansajtos** [comment]
ci:test:search:norebase

**Comment by istvansajtos** [comment]
ci:test-es7:norebase

**Comment by istvansajtos** [comment]
ci:help

**Comment by istvansajtos** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/85765

**Pull request closed without merging**
