### PR TITLE
LPS-65291

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-65291

### CODE REVIEW

**Comment by ChrisKian** [comment]
I'll refactor the tests a bit and re-push first thing tomorrow.

**Comment by ChrisKian** [comment]
Added the following changes:

-Rebased to current master HEAD
-testFindPreviousAndNext() is now split into four different test methods with more descriptive names.
-generateBlogsEntries renamed to generateAndTestBlogsEntries
-Import dependencies required for the final commit are now in said commit.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/986

**Pull request closed without merging**
