### PR TITLE
LPS-67454 Trash Portlet should be accessible from page scope

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-67454

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
is there another way to identify the portlet other than its display name?

**Comment by ChrisKian** [comment]
I used a better way for checking the portlet's class

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/1029

**Pull request closed without merging**
