### PR TITLE
LPS-177664 Concurrent Reindex (with Blue/Green UI)

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search-environments

**Comment by xbrianlee** [comment]
ci:test:search-remote-minimum

**Comment by xbrianlee** [comment]
ci:test:search-remote

**Comment by xbrianlee** [comment]
ci:close

Continued in https://github.com/liferay-search/liferay-portal/pull/893

**Pull request closed without merging**
