### PR TITLE
2020_09_01_LPS_115435_pagination_delta

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:relevant:norebase

**Comment by BryanEngler** [comment]
@thektan fyi you might want to check this, i think the regression was caused by https://issues.liferay.com/browse/LPS-98391

**Comment by thektan** [comment]
@BryanEngler Thanks for fixing that! Can you also make the same change to https://github.com/BryanEngler/liferay-portal/blob/2020_09_01_LPS_115435_pagination_delta/portal-web/docroot/html/taglib/ui/page_iterator/start.jsp#L240?

**Comment by BryanEngler** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by BryanEngler** [comment]
ci:test:relevant:norebase

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
