### PR TITLE
LPS-173591 pagination with permissions

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
Hey @BryanEngler, Bchan said to me and Felipe that end and start variables should not be changed inside [ElasticsearchIndexSearcher](https://github.com/liferay/liferay-portal/blob/df5711d5680f96b79abb868f51307a6f9b3a35bd/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/ElasticsearchIndexSearcher.java#L83-L113).

Tested your code here and it works, so looks to me that this code linked is unnecessary. Because I debugged and it just change the end and start to the same values as before.

Do you think we can remove it?

**Comment by BryanEngler** [comment]
i dont think we can remove that code because there are 2 different ways to set the "from" and "size". through the searchContext, or through the searchRequest. i found a test that sets the values through the searchRequest. if you delete that block of code, this test will fail

AccountEntryLocalServiceTest.testSearchPagination

**Comment by gustavolimav** [comment]
@BryanEngler that behavior looks weird to me, don't you think?

https://user-images.githubusercontent.com/76820333/222541188-8d40fff6-2bfb-48d0-ad91-63f818691452.mp4

**Comment by joshuacords** [comment]
Hi @gustavolimav, that behavior is expected if the Search Accurate Count Threshold isn't set (in System Settings > Search). If setting the threshold to more than 20 in this case makes the changing result numbers go away then it's fine.

**Comment by joshuacords** [comment]
Hi @gustavolimav,

Does this test insure that setting **Search Accurate Count Threshold ** will check all the documents instead of only the first 4 (to the first page)?

**Pull request closed without merging**
