### PR TITLE
LPS-59248 - Integration test

### PR DESCRIPTION
**Pull request by ericyanLr**
Reference: https://github.com/brianchandotcom/liferay-portal/pull/30953#issuecomment-147778592

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/852

**Pull request closed without merging**
