### PR TITLE
pr_2020_02_06_pr476_LPS_108052_solr_prefilter Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by joshuacords** [comment]
Hi @BryanEngler,
Are you concerned about anything in particular with this pull. From what I see all the test failures seem unrelated or documented on the Test Analysis sheet

**Comment by BryanEngler** [comment]
no i think its probably good to go, just been busy with ccr backports so i havent forwarded it yet. i guess my only question would be if you verified that it actually fixes the issue since there was a question that it maybe didnt?

**Comment by joshuacords** [comment]
I just verified that it's working. You're good to send it up. :)

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84556

**Pull request closed without merging**
