### PR TITLE
2020_03_19_LPS_110604_ccr_cluster_ids Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

🤞

**Comment by xbrianlee** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@xbrianlee @BryanEngler I merged this into my origin even though it broke relevant because @xbrianlee told me to.

@BryanEngler can you change:

Configure the Operation Mode in the Elasticsearch...

to

Configure the operation mode in the Elasticsearch...

It would be like sayng, please set Tomcat's port to 8123. You would never say: "please set Tomcat's Port to 8123".

Tomcat is a proper noun and port is not a proper noun.

Please fix usages and send me a follow up pull.

**Comment by BryanEngler** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/86937

**Pull request closed without merging**
