### PR TITLE
2020_06_22_LPS_109110_112607_106093_sidecar_refactor Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Continuing testing in https://github.com/xbrianlee/liferay-portal/pull/480

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
