### PR TITLE
Commit to Fix broken tests on LPS-200654

### PR DESCRIPTION
**Pull request by AlmirFe**

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:reopen

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
cherry picked to https://github.com/liferay-search/liferay-portal/pull/1204, thanks

**Pull request closed without merging**
