### PR TITLE
[TECHNICAL SUPPORT] LPS-102947 baseline

### PR DESCRIPTION
**Pull request by rodrigopaulino**
According André's notes on https://github.com/rodrigopaulino/liferay-portal/pull/22#issue-340207743, check [the changes](https://github.com/BryanEngler/liferay-portal/pull/446/commits/a520c4bb6936b31f4fd211d712f6fa22a23afc53#diff-488ce1abefc21bf39dd3a7e5916dd2e1R184-R193) I've made on the original proposal. I did that because the `defaultValue` would only be used when `document.get("resourcePermissionName")` was `null` and this was causing other DDM tests to fail.

Also, I've changed from `PortalException` to `Exception` [here](https://github.com/BryanEngler/liferay-portal/pull/446/commits/6bebaa6a07c89f970119e85ca28fa1697a94e70e#diff-8c82cb4dab102bb69681d49aa7a96d3bR182-R186) to maintain the original behavior as suggested.

Finally, I have removed our changes on the previous DDM tests and introduced a new one that contemplates this bug. See https://github.com/BryanEngler/liferay-portal/pull/446/commits/190c2326f11a9d862fb88fbe848849885b8cd726

cc/ @arboliveira

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:search

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
looks good to me, im running one more CI batch (https://github.com/BryanEngler/liferay-portal/pull/448) before sending to bchan

**Pull request closed without merging**
