### PR TITLE
LPS-136104 Update synonym settings

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-remote

**Comment by BryanEngler** [comment]
ci:test:search-remote-minimum

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:reevaluate:1257401_3225

**Comment by joshchong** [comment]
@BryanEngler the test results look good.

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
