### PR TITLE
2019_11_19_LPS_97585_expando_keyword Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by katienesterovich** [comment]
Hey @BryanEngler,
I tested your solution on [LPS-97585](https://issues.liferay.com/browse/LPS-97585) and it doesn't fix the issue. 
Here is what I did: 
1) Rebase to master, `git clean -xdf`, and `ant all`
2) Cherry-pick your commits and `gw clean deploy` them
3) Shut down the server, clear server cache (delete osgi/state, tomcat/temp, tomcat/work, and data folders).
4) Clear my database
5) Restart server, reindex and replicate steps from LPS-97585
6) Getting the same issues as in LPS-97585 (no results and terminal error). 
7) Reindex again (to double check) and clear browser cache - still replicating the bug

**Comment by BryanEngler** [comment]
hi @katienesterovich 
did you enter `expando__keyword__custom_fields__myfield.raw` as the "Aggregation Field" in the Custom Facet configuration?

https://github.com/BryanEngler/liferay-portal/pull/441#issuecomment-555886765

**Comment by katienesterovich** [comment]
@BryanEngler I did not, I used `expando__keyword__custom_fields__myfield`. Let me try it again with that modification.

**Comment by katienesterovich** [comment]
@BryanEngler It works with that modification! My apologies, didn't catch that originally.

**Comment by BryanEngler** [comment]
@katienesterovich sounds good. im just gonna run one more set of tests and then forward to bchan later today

**Comment by BryanEngler** [comment]
ci:test:search:543c4a926d8eae4e83c6bd09d5ffaf95159ca247

**Comment by BryanEngler** [comment]
ci:test:search-es7:543c4a926d8eae4e83c6bd09d5ffaf95159ca247

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/81183

**Pull request closed without merging**
