### PR TITLE
2020_01_08_LPS_106783_upgrade_config Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:search-es7:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by xbrianlee** [comment]
@BryanEngler I'm still noticing that `authenticationEnabled` returns to "false"

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
@xbrianlee this should be ready to test again

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search-es7:norebase

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Pull request closed without merging**
