### PR TITLE
LPS-163750 Create API to get search indexes

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@wcao20170619 let me know if this looks good to you

**Comment by wcao20170619** [comment]
> @wcao20170619 let me know if this looks good to you

Nice!

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
will probably forward https://github.com/liferay-search/liferay-portal/pull/616 first because i think it might conflict with this pr and that task has higher priority

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
