### PR TITLE
LPS_84440_new_groupBy_api Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
> ### ❌ ci:test:search - 15 out of 17 jobs passed in 1 hour 34 minutes 8 seconds 172 ms
> Click here for more details.

## ANALYSIS
### Jenkins Report
https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3743/jenkins-report.html
### Failed Batches
* js-unit-jdk8: failure on dynamic-data-mapping-form-builder

**Pull request closed without merging**
