### PR TITLE
LPS-138944 Web content highlighting

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-remote

**Comment by BryanEngler** [comment]
ci:test:search-remote-minimum

**Comment by joshuacords** [comment]
Looks good @BryanEngler, thanks for reviewing.

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
@joshuacords we might have a functional test failure here... PreviewScheduledWebContentInWCD ?

gonna try forward one more time

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
