### PR TITLE
[TS LPS-97491] | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi @BryanEngler 

This issue is related to LPS-92477 about how to generate tags and categories links in search portlet results.
In this case we need take into account when portal is behind a front-end web configured with SSL termination.

References:
https://issues.liferay.com/browse/LPS-97491

KR, 
 Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Do you have any update about this PR?

Thank you

**Comment by BryanEngler** [comment]
hey guys, ill take a look on monday, thanks!

**Comment by jorgediaz-lr** [comment]
Thank you, @BryanEngler

**Comment by lipusz** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/375

**Pull request closed without merging**
