### PR TITLE
LPS-59478

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
test failures don't appear to be related to my changes

**Comment by arbetts** [comment]
i'm also sending a plugins pull for this LPS (not for failures, but because they also use the outdated pattern

**Comment by BryanEngler** [comment]
other than a little SF it seems to be good. just waiting on the question for plugins and then ill send them together

**Comment by BryanEngler** [comment]
i got a merge conflict when rebasing to master. can you rebase and push again?

**Comment by arbetts** [comment]
kk ... will resend after rebase

**Comment by arbetts** [comment]
@BryanEngler 

rebased and updated pull

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/850

**Pull request closed without merging**
