### PR TITLE
[TS] LPS-94230 Search results are not visible when paginating on JBoss/Wildfly

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-94230](https://issues.liferay.com/browse/LPS-94230)

Hi Bryan,

I am sending this to you as [Tibor Lipusz suggested it](https://github.com/lipusz/liferay-portal/pull/263#issuecomment-484524344).

**Issue:**
Results disappear in Search Results portlet when switching between pages  on JBoss/WildFly (and probably Websphere too). The reason is that SearchContainer._iteratorURL doesn't contain the search keyword (q parameter).

**Technical Background:**
The issue originates from the **incorrect assumption** that PortalImpl.getOriginalServletRequest(HttpServletRequest) returns the "original request" carrying the URL, query string, etc. as it comes from the browser.

The request (in recent scenario a RenderRequest) we retrieve the original URL and query string from is wrapped multiple times and went through several RequestDispatchers. I found no info in [Servlet 3 specification](https://download.oracle.com/otn-pub/jcp/servlet-3.0-fr-eval-oth-JSpec/servlet-3_0-final-spec.pdf) what to expect from the current approach of unwrapping the "original request" (done by PortalImpl.getOriginalServletRequest(HttpServletRequest)). The specification, however, describes how to access the properties of the "original request" (facing the very first servlet) in case of forwarded/included requests.

> 9.3.1 Included Request Parameters
> 
> ...
> 
> The following request attributes must be set:
> 
> javax.servlet.include.request_uri
> javax.servlet.include.context_path
> javax.servlet.include.servlet_path
> javax.servlet.include.path_info
> javax.servlet.include.query_string
> 
> These attributes are accessible from the included servlet via the getAttribute method on the request object and their values must be equal to the request URI, context path, servlet path, path info, and query string of the included servlet, respectively. If the request is subsequently included, these attributes are replaced for that include.

> 9.4.2 Forwarded Request Parameters
> 
> ...
> 
> The following request attributes must be set:
> 
> javax.servlet.forward.request_uri
> javax.servlet.forward.context_path
> javax.servlet.forward.servlet_path
> javax.servlet.forward.path_info
> javax.servlet.forward.query_string
> 
> The values of these attributes must be equal to the return values of the HttpServletRequest methods getRequestURI, getContextPath, getServletPath, getPathInfo, getQueryString respectively, invoked on the request object passed to the first servlet object in the call chain that received the request from the client.
> These attributes are accessible from the forwarded servlet via the getAttribute method on the request object. Note that these attributes must always reflect the information in the original request even under the situation that multiple forwards and subsequent includes are called.

**How I understand the spec:** 
If the request was forwarded, then the properties (request URI, context path, servlet path, path_info, query_string) of the originally sent request are preserved by the javax.servlet.forward.* attributes. For included request we can call the getter methods directly on the request as they return the values belonging to the originally sent request. That is, we have to handle distinctively only the case of forwarded requests.

**Automated tests:**
I think this issue cannot be covered by automated tests. At least, I couldn't figure out how this application server specific request dispatching issue could be tested in connection with search or more generally via PortalUtil. Please let me know if you have an idea.

Thanks for reviewing,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
without really looking at the code yet, the first thing i would say is that in search we try to avoid making changes to portal-kernel at pretty much all costs, so you do think you could try to rework the solution to only make changes to search modules?

**Comment by istvansajtos** [comment]
Thanks @BryanEngler! I will double-check if leaving portal-kernel intact is possible.

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
