### PR TITLE
[TS] LPS-92477 | master

### PR DESCRIPTION
**Pull request by samanzanedo**

### CODE REVIEW

**Comment by samanzanedo** [comment]
Hello, @BryanEngler 

I  sent to you the PR because of in a previous one you were also assigned by  @lipusz
 (See https://github.com/arboliveira/liferay-portal/pull/733)

Reference:
https://issues.liferay.com/browse/LPS-92477

Kind regards.

/cc @arboliveira
/cc @ricardocousolr

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
Hello, @BryanEngler 

What modifier is needed by the SF error?

Kind regards,
 Sergio.

**Comment by BryanEngler** [comment]
@hhuijser looks like source formatter might be trying to enforce modifiers this local class? which would cause a compile error https://docs.oracle.com/javase/specs/jls/se9/html/jls-14.html#jls-14.3

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/361

**Pull request closed without merging**
