### PR TITLE
LPS-83585 Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:solr

**Comment by xbrianlee** [comment]
ci:test:solr

**Comment by xbrianlee** [comment]
@BryanEngler Test failures are unrelated (Solr configuration issues). See results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=409284409).

**Comment by BryanEngler** [comment]
ci:test:es2

**Comment by arboliveira** [comment]
Reviewed, submitted as https://github.com/brianchandotcom/liferay-portal/pull/62445. Thanks!

**Pull request closed without merging**
