### PR TITLE
LPS-162241 Context Vars

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@BryanEngler 

https://github.com/BryanEngler/liferay-portal/pull/667/commits/f7237da8037c68ad27628b6cf64722da2168086b

That commit is causing the failure.

We need to do a validation because when statusByUserId and userId is 0 it returns a Nullpointerexcption

**Comment by gustavolimav** [comment]
@BryanEngler https://github.com/BryanEngler/liferay-portal/pull/671

**Comment by BryanEngler** [comment]
> We need to do a validation because when statusByUserId and userId is 0 it returns a Nullpointerexcption

@gustavolimav this doesnt sound right... the fetch* methods either return an object, or they return null. maybe since this is a unit test the userLocalService is what is null, so we need to probably set/mock it

**Pull request closed without merging**
