### PR TITLE
LPS-187194: Sync SearchHits with the permission filtered kernel search Hits

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by wanderlast** [comment]
Hi @BryanEngler,

Are we still waiting for further testing on this issue? I want to make sure I'm conveying what's going on to the client properly. Thanks!

**Comment by BryanEngler** [comment]
@wanderlast ya there are some failing tests so im still working on resolving those

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:stop

**Pull request closed without merging**
