### PR TITLE
LPS-104014

### PR DESCRIPTION
**Pull request by lipusz**
/cc @yxingwu

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/86646

**Pull request closed without merging**
