### PR TITLE
2019_03_22_LPS_92341_SearchEngineAdapterTest_failure Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
> ### ❌ ci:test:search - 13 out of 17 jobs passed in 1 hour 28 minutes 55 seconds 636 ms
> Click here for more details.

## ANALYSIS
### Jenkins Report
https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3743/jenkins-report.html
### Failed Batches
* functional-tomcat90-mysql57-jdk8:
  * Test runtime failure. Fluke.
* js-unit-jdk8:
  * js-unit-jdk8 tests failing due to FragmentsEditorIdUtils & portal-workflow-metrics-web
### Unstable Batches
* modules-integration-mysql57-jdk8:
  * Per Bryan, "the only changes in that pr are in the `SearchEngineAdapterTest` class itself." This shouldn't be cause for concern. Re-running the PR just in case.

**Comment by BryanEngler** [comment]
ci:test:sf

**Pull request closed without merging**
