### PR TITLE
LPS-65342

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-65342

Made changes based off Julio's comments here: https://github.com/juliocamarero/liferay-portal/pull/4140

### CODE REVIEW

**Comment by ChrisKian** [comment]
One of the failed tests was my fault, let me re-push

**Comment by ChrisKian** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @BryanEngler @ChrisKian 

since the code only affects Announcemnts, could you please send the final pull to the Collaboration Team?

Thank you!

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/978

**Pull request closed without merging**
