### PR TITLE
2020_02_07_LPS_108303_connections_ui Test

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
Hey @BryanEngler, the only failure i'm not sure about from the two test runs above is the modules-int test within ci:test:search-es7 `DepotEntrySearchTest.testSearchBothWithPermissions`. Can you take a look? All other failures are unrelated.

**Comment by BryanEngler** [comment]
seems odd that it would fail since this pr is only making UI changes... but ill check it out

**Comment by joshchong** [comment]
oh actually it looks like that test is flakily failing upstream. You should be able to safely ignore it:
https://testray.liferay.com/home/-/testray/cases/983364660

**Comment by BryanEngler** [comment]
@joshchong i ran the test locally on master 5 times. it failed 2 out of the 5 times. so its probably an issue with the test not making sure that documents have enough time to be indexed before searching for them...

i also ran the test 5 times with this branch. it actually passed all 5 times, which isnt surprising since this pr only changes UI...

**Comment by BryanEngler** [comment]
> oh actually it looks like that test is flakily failing upstream. You should be able to safely ignore it:
> https://testray.liferay.com/home/-/testray/cases/983364660

ninja'd

**Comment by joshchong** [comment]
thanks for checking tho, it helps confirm it's a problem with the test.

**Pull request closed without merging**
