### PR TITLE
[TS] LPS-107382 searchResponse.getSearchHits() can return null

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-107382

[ci:test:search - 45 out of 50 jobs passed](https://github.com/joshuacords/liferay-portal/pull/63#issuecomment-576502979) - the bad tests were also failing in master

Authors: @joshuacords

**Problem:** In the case that a Search is done without setting `searchRequestBuilder.emptySearchEnabled(true);` or a keyword, the search can be fast returned without searchResults in [FacetedSearcherImpl](https://github.com/liferay/liferay-portal-ee/blob/71cb7096968c8c3081cd072458760cfe5b30db89/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/searcher/FacetedSearcherImpl.java#L126-L132). This causes getSearchHits() to return null.

**Solution:** Instead return empty searchHits similar to [getDocumentsStream()](https://github.com/liferay/liferay-portal/blob/9a4519d39a2b8dd8448163b6462ee7d60b43d63c/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/searcher/SearchResponseImpl.java#L89-L100).

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:relevant:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Comment by joshuacords** [comment]
ci:test:relevant:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
@joshuacords this breaks the `SearchResponseImplTest.testDefaultsAreNullSafe` unit test.
should be an easy test fix, but first maybe we should investigate if there is any reason that the test is actually expecting the default value to be null

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/475

**Pull request closed without merging**
