### PR TITLE
LPS-93762 Reindex the SYSTEM company index as well 

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-93762

Hey Bryan,

I've simplified Mike's original changes (https://github.com/lipusz/liferay-portal/pull/269) because personally I don't think we need a new API for this.

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
just curious, what was the deal with ReplicasManagerImplTest? does it have coverage on this issue?

**Comment by lipusz** [comment]
I believe it'd fail, though it `@Ignored` currently

**Comment by lipusz** [comment]
We discussed this on Slack (April 10, team-search-dev) ;-)

**Comment by lipusz** [comment]
Actually, it might pass, though the reindex admin is not using the replicas manager API, though I'm not sure.

**Comment by BryanEngler** [comment]
ya i mean thats a unit test in elastic, nothing in this pr is changing that...

sent to bchan https://github.com/brianchandotcom/liferay-portal/pull/73970

**Pull request closed without merging**
