### PR TITLE
LPS-183165: Create indices only after successful company registration. Delete on company unregistration.

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by brookedalton** [comment]
ci:test:stable

**Pull request closed without merging**
