### PR TITLE
LPS-67824 Use writeObject instead of writeUTF to handle entries that are longer than 65535 bytes

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by BryanEngler** [comment]
did you look into any of the other usages of writeUTF to see if they should be changed?

**Comment by BryanEngler** [comment]
ci:retest

**Comment by ericyanLr** [comment]
Hey Bryan,

I did look through other usages of writeUTF and most of them are are cacheModels.  I'm actually not familiar with those, do you know if those could be problematic?

A few that may run into this issue other than the cacheModels, are:
* StringTemplateResource.java
* XSLTemplateResource.java

Basically anything that exceeds the length of 65535 bytes would encounter this issue.
But, I am not certain what those classes actually do and if they can create a length of 65535 bytes.

Should I research on how to use those classes and test if this issue can cause an issue for those?

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/1045

**Pull request closed without merging**
