### PR TITLE
Lps 74642 lps 74653 - Added Tests and modified mapping for Japanese search

### PR DESCRIPTION
**Pull request by yasuflatland-lf**
Lps 74642 lps 74653 - Added Tests and modified mapping for Japanese search

### CODE REVIEW

**Comment by austinchiang** [comment]
@BryanEngler Do you have bandwidth to review this pull soon? Thanks!

**Comment by BryanEngler** [comment]
Hey @austinchiang, I have reviewed it and actually have another dev branch that I've added more tests to - https://github.com/BryanEngler/liferay-portal/commits/LPS-74642_LPS-74653-mappings.

I have also been in contact with Yasu on an email thread about this, sorry for not giving any updates here on the pr.

We should be close to resolving the issue, we just need to Yasu to reconfirm what the expected search results should be after his findings here - https://issues.liferay.com/browse/LPS-74642?focusedCommentId=1191495&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1191495

Thanks

**Comment by austinchiang** [comment]
Gotcha, thank you for the update!

**Comment by BryanEngler** [comment]
reviewed and sent to andre - https://github.com/arboliveira/liferay-portal/pull/351

**Pull request closed without merging**
