### PR TITLE
LPS-59784

### PR DESCRIPTION
**Pull request by ssmith353**

### CODE REVIEW

**Comment by BryanEngler** [comment]
a few questions - 
1) is the "SharedImages" part of the path something that comes from liferay, or the customer, or MediaWiki? basically just wondering if this value could ever change

2) did you look into why the request doesnt contain the "correct" file name for the fileName parameter?

3) is it possible that the path would have subdirectories under SharedImages?

4) why does title need to be set to "SharedImages"?

**Comment by BryanEngler** [comment]
looks like the answer to #1 is to use MediaWikiImporter.SHARED_IMAGES_TITLE

**Comment by ssmith353** [comment]
Hey Bryan, upon import: https://github.com/liferay/liferay-portal-ee/blob/ee-6.2.x/portal-impl/src/com/liferay/portlet/wiki/importers/mediawiki/MediaWikiImporter.java#L321 we add it to a page in the root node, named "SharedImages" 

The request is from the page, which we replaced the URL for the image from being the original content to be a relative URL to the SharedImages page. So the "title" in the request for the image is "SharedImages/image.jpg." and we try to fetch the image from the page nodeID, which is the incorrect page, so I changed the title to be the "SharedImages" page, so it can fetch the image from the correct NodeId.

**Comment by ssmith353** [comment]
And, for 3) No, the import is hard coded to be in the root node, on the SharedImages page, and should only be created if it's been imported from MediaWiki.

**Comment by ssmith353** [comment]
Here is where we create the relativeURL's for {SharedImages/image.jpg} 

https://github.com/liferay/liferay-portal-ee/blob/ee-6.2.x/portal-impl/src/com/liferay/portlet/wiki/translators/MediaWikiToCreoleTranslator.java#L210

**Comment by BryanEngler** [comment]
k. i think i pretty much understand the whole process now... to me it seems like we dont "support" referencing attachments from other pages in general... as an example, what if you try this with images that arent imported? lets say i create two pages... on page one i attach a file "foo.png". in page two i add {{one/foo.png}} to the source. in this case the image also isnt displayed...

basically i was just wondering if we should implement this behavior for all images, or only for ones that are imported into this SharedImages page... and i think for now it should only be the imported images... there are still some other inconsistencies but i think this should be an acceptable fix for this part of the issue.

ill sf a little and send to mccann

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/856

**Pull request closed without merging**
