### PR TITLE
LPS-92486

### PR DESCRIPTION
**Pull request by brianikim**
Notes from @matthewchan123:

> https://issues.liferay.com/browse/LPS-92486
> 
> Issue:
> Configuring search bar widget with a destination page friendlyURL that has non-ascii chars results in "This search bar is not visible to users yet. Set up its destination to make it visible."
> 
> Cause:
> Created layouts have utf-8 encoded friendlyURL fields. Although we have handled encoding correctly for adding, getting and updating Layouts, we forgot to do so for fetchLayoutByFriendlyURL. The mismatch causes fetchByG_P_F_Head to return null, thus the destination page appears unreachable.
> 
> Fix:
> In order to fix this issue, we can make use of helper method [getFriendlyURL()](https://github.com/liferay/liferay-portal/blob/62f42f454a8485b3d7a5b41d67b1822002a4b53c/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceHelper.java#L116). The returned String will have utf-8 encoding. After adding this change, search bar widget can accept non-ascii characters in destination pages.

PR was directed to you as per @lipusz

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:search

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test

**Comment by lipusz** [comment]
Hey Brian,

I didn't look into the changes on the other PR but now as I can see you are not changing anything in the search components, but in layouts only so I believe it's better to forward it to Eudaldo or to the WEM SME.

**Comment by brianikim** [comment]
Hello @lipusz ,

I will do the redirect once the ci:tests complete.

Sincerely,
Brian Kim

**Comment by lipusz** [comment]
You don't need to run ci:test, it's heavy, ci:test: relevant is enough ;-)

**Comment by brianikim** [comment]
ci:stop

**Pull request closed without merging**
