### PR TITLE
LPS-76799 [TECHNICAL SUPPORT]

### PR DESCRIPTION
**Pull request by jcampoy**
Hi @BryanEngler , here you have a separated fix for the issue with the null word.

Could you take a look and resend this PR and https://github.com/arboliveira/liferay-portal/pull/364 with out your commits about this issue? 

Many thanks for your help.

Best regards,

### CODE REVIEW

**Comment by BryanEngler** [comment]
hey @jcampoy 
thanks for looking into this. im testing your changes that allow a blank line to be added to the dictionary file, and im getting this exception:
`Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.liferay.portal.search.suggest.DictionaryReader$DictionaryIterator.next(DictionaryReader.java:87)
	at com.liferay.portal.search.suggest.DictionaryReader$DictionaryIterator.next(DictionaryReader.java:56)
	at com.liferay.portal.search.suggest.BaseGenericSpellCheckIndexWriter.indexKeywords(BaseGenericSpellCheckIndexWriter.java:143)`

also, i think if a dictionary file ends with more than one blank line, the previous batch of words will not get indexed.

but ill continue looking at it to see if i can resolve these issues and let you know what i come up with

**Comment by jcampoy** [comment]
Hey @BryanEngler , I can take a look today and resend the PR :)

Thanks!!

**Comment by jcampoy** [comment]
HI @BryanEngler , I've fixed the problems you found and I've just updated the PR.

Thanks!!!

**Comment by jcampoy** [comment]
Hi @BryanEngler , we have delivered this as a temporary fix, Could you take a look to the PR? or include a similar fix in your other PR? 
BR,

**Comment by BryanEngler** [comment]
Hey @jcampoy, sounds good, i spent some time yesterday writing tests for this issue, i should be done with them today. we will be applying the changes on top of LPS-76500 so that we dont modify portal-kernel. i will let you know when i forward the pr to andre. thanks again

**Comment by BryanEngler** [comment]
sent to andre https://github.com/arboliveira/liferay-portal/pull/373

**Comment by wcao20170619** [comment]
[Search Administration: move "Indexing Actions" from Server Administration](https://trello.com/c/cu2ZmLuv/482-search-administration-move-indexing-actions-from-server-administration)

**Pull request closed without merging**
