### PR TITLE
LPS-153813 backend current status of implementation

### PR DESCRIPTION
**Pull request by wcao20170619**
@BryanEngler I squashed your changes - very nice and thx! Also, I attached a tmp commit that has all the implementation for the backend that I have added so far. I am going to continue to work on this branch and let you know when I add something new. BTW if you would like to have a separate branch(PR) for LPS_163750, please let me know. Thanks!

### CODE REVIEW

**Comment by wcao20170619** [comment]
updated to add an external flag and include external indexes in the list of getName

**Comment by wcao20170619** [comment]
@BryanEngler for the following part,  the external indexes are not by contextCompany. It looks like this for all the companies.  So we will list all the external indexes at UI? and if it is yes,  we may save it as it is along with the "external" flag. right?
	/*
		TODO
		 Get "external" indexes that are searchable by contextCompany (as
		 defined by a new configuration or some other mechanism) and add them to
		 searchIndexes with external = true;
		*/

**Comment by wcao20170619** [comment]
So what do we do about that now? Just leave the flag there?

**Comment by BryanEngler** [comment]
ya so i think we can forward the commits on this pr that are before the TODO commit, and then either create a new subtask or use one that you are already working on to set the index name in the builder. we will probably have to talk to tibor to see if he wants to include external indexes in this story or not.

**Comment by BryanEngler** [comment]
i will create a new pr that can be forwarded

**Comment by BryanEngler** [comment]
actually i just noticed you are prepending `external:` to the index name in this pr... i dont think we need to do that, the flag should be enough. so ill just squash the commits from https://github.com/wcao20170619/liferay-portal/pull/146 (minus everything after the TODO) and send that

**Comment by wcao20170619** [comment]
I have reverted back to the original after the last talk. for both unit test and implementation class.

**Comment by BryanEngler** [comment]
https://github.com/BryanEngler/liferay-portal/pull/705

**Comment by wcao20170619** [comment]
you are correct!

**Pull request closed without merging**
