### PR TITLE
LPS-66646

### PR DESCRIPTION
**Pull request by gregory-bretall**

### CODE REVIEW

**Comment by BryanEngler** [comment]
i wasnt exactly sure on some of the js stuff so im checking with byran

**Comment by blzaugg** [comment]
@gregory-bretall,

Please review the discussion at: https://github.com/jonmak08/liferay-portal/pull/1592

I believe this is a complete solution, that @jonmak08 provided (sorry it's been a while): https://github.com/zxdgoal/liferay-portal/pull/15

If it's not a complete solution, please follow it through to completion.

Do we know why @zxdgoal didn't follow up on this?

**Comment by zxdgoal** [comment]
The fix about LPS-66646 is almost done.

But I have been busy with LPPs during these two month as we have a Japanese customer keep creating tickets about DXP.

So the fix is delayed.

@gregory-bretall 

If you are not in a hurry, I will try to fix it in two days.

Thanks
JOhn.

**Comment by gregory-bretall** [comment]
There's no particular hurry for this file, it can wait two days.

**Comment by BryanEngler** [comment]
closing since it looks like we will either use LPS-52814 or https://github.com/zxdgoal/liferay-portal/pull/15

**Pull request closed without merging**
