### PR TITLE
LPS-90881 Update test cases to handle if there are other IndexerPostProcessors in the system

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-90881

Hey Bryan,

This primarily affects 7.1.x, though I don't see any problem with having it on master too.

Author: @gamerson
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:search:test

**Comment by lipusz** [comment]
Hey @BryanEngler 

I can send it to Brian just let me know if you're okay with that. Thanks!

**Comment by BryanEngler** [comment]
sorry it took a while, sent to bchan https://github.com/brianchandotcom/liferay-portal/pull/69330

**Pull request closed without merging**
