### PR TITLE
LPS-97585

### PR DESCRIPTION
**Pull request by brianikim**
Notes from @katienesterovich:

> https://issues.liferay.com/browse/LPS-97585
> 
> Fix adds a normalizer for indexing which converts all keywords to lowercase values - this returns hits in all lowercase and guarantees that we find matches regardless of their case.
> 
> For example,
> 
>     * ```
>          `dog`, `Dog`, `DOG` entries are converted to `dog` for indexing
>       ```
> 
>     * ```
>          Searching for `dog`, `Dog`, or `DOG` --> returns all 3 entries
>       ```
> 
> 
> I verified that the fix works and ran source formatter, rebased to master.
> 
> Fix does not break related [LPS-69574](https://issues.liferay.com/browse/LPS-69574).
> 
> Note: to verify, deploy and Reindex all searches indexes in Control Panel > Configuration > Search

Resent from https://github.com/SamZiemer/liferay-portal/pull/695 to address concerns with integration tests.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
FYI the changes will also have to be applied to the elasticsearch 7 module

**Comment by brianikim** [comment]
Did you want me to re-push with the es7 changes after testing is complete?

**Comment by BryanEngler** [comment]
i dont know what exactly we were trying to accomplish with the original expando mappings, but take a look at https://github.com/BryanEngler/liferay-portal/pull/442 and test it out to make sure it covers everything you need for the LPS/LPP

it would require that you enter `expando__keyword__custom_fields__myfield.raw` as the  "Aggregation Field" in the Custom Facet configuration

**Comment by brianikim** [comment]
Hello @BryanEngler ,

I just want to make sure I understand clearly. From my understanding, #442 is the solution that you wish to push forward right? The commits here can be discarded once I test #442 ?

Sincerely,
Brian Kim

**Comment by BryanEngler** [comment]
@brianikim 
correct. the solution in this pr still has some case sensitivity problems etc... i think the solution in 442 is both simpler and works better. let me know what you think!

**Comment by brianikim** [comment]
Closing this in advance and testing #442

**Pull request closed without merging**
