### PR TITLE
[TS] LPS-104673

### PR DESCRIPTION
**Pull request by hudakl**
Hi Bryan,

I'm sending you this pull as a followup of this one: https://github.com/lipusz/liferay-portal/pull/295
Could you please review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by hudakl** [comment]
Hi Bryan,

Do you have any updates on the review?

Thanks,
Laci

@BryanEngler

**Comment by BryanEngler** [comment]
i will be taking a look tomorrow!

**Comment by BryanEngler** [comment]
i forgot, actually we are going to be at the elastic conference all day tomorrow, i will look on friday

**Comment by BryanEngler** [comment]
running some tests here https://github.com/BryanEngler/liferay-portal/pull/482

**Pull request closed without merging**
