### PR TITLE
LPS-61079

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
you think throwing an IllegalArgumentException would make more sense than a NullPointerException?

**Comment by arbetts** [comment]
i was throwing the NPE because it was null, but an IllegalArgumentException also makes sense.

**Comment by BryanEngler** [comment]
ya i think either one is applicable...

**Comment by BryanEngler** [comment]
what we need is a NullArgumentException haha... i dont think any of the failed tests are related but ill wait til this next one finishes and then pass it to mccann

**Comment by arbetts** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Comment by arbetts** [comment]
pushing a rebase and will retest

i think these errors are coming from some of the other commits on the branch... hoping that rebasing will fix some of these

**Comment by arbetts** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ok. last chance. if it fails again im just gonna close the pr haha

**Comment by BryanEngler** [comment]
i dont see the thing that says tests are running...

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
i think the errors are consistent enough to conclude that your pr is causing them so im gonna go ahead and close this

**Comment by arbetts** [comment]
these are selenium failures so i'm not sure how the xml parser effects it ... they are consistent, but seem very unrelated

at com.liferay.poshi.runner.PoshiRunnerExecutor.runSeleniumElement(PoshiRunnerExecutor.java:724)

**Comment by arbetts** [comment]
i think we found it ... no return statement on the char[] read method.

will resend

**Pull request closed without merging**
