### PR TITLE
LPS-107863 NoNodeAvailableException using Elasticsearch 7 with SSL/TLS on JDK 11 (Transport Client only)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-107863

Hello Bryan,

Master/7.3.x is not affected because we are using the REST client for ES7, so sending just to have a nice history. ;-)

:heavy_check_mark: `ci:test:sf` : Passed https://github.com/lipusz/liferay-portal/pull/296
:white_check_mark: `ci:test:search-es7` : Passed with no relevant failures on https://github.com/lipusz/liferay-portal/pull/296, checked with @xbrianlee

Note: currently @xbrianlee is working on to run the ES7 tests with JDK 11 (so to use the same JDK that the portal is using) otherwise the problem is not reproducible on 7.2.x either.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Thanks to @xbrianlee now it's [reproduced on 7.2.x](https://github.com/xbrianlee/liferay-portal-ee/pull/232#issuecomment-580873989) after some changes to the test configuration.

**Comment by xbrianlee** [comment]
Running `search-es7` suite (JDK11 variant) and these changes in this PR
https://github.com/xbrianlee/liferay-portal-ee/pull/232#issuecomment-580936442

**Comment by lipusz** [comment]
Actually, we could send the test changes together with this PR to Bryan, right, @xbrianlee? I can cherry-pick your changes unless you want to send them separately for `master`.

**Comment by xbrianlee** [comment]
Actually my changes in that PR are very informal. We'll have to create these suites:
- https://issues.liferay.com/browse/LRQA-55465
- https://issues.liferay.com/browse/LRQA-55466

**Comment by xbrianlee** [comment]
**Test Results**
❌ ci:test:search-es7 - 40 out of 43 jobs passed in 1 hour 34 minutes 30 seconds 62 ms
https://github.com/xbrianlee/liferay-portal-ee/pull/232#issuecomment-580960440
- `ClassicSearch#SearchTwiceScopeLetUserChoose` failed due to SPA fluke
-  [CLDSVCS-4071](https://issues.liferay.com/browse/CLDSVCS-4071) ModuleConfigurationLocalizationTest.testConfigurationLocalization on LCS
- Verified that `org.elasticsearch.client.transport.NoNodeAvailableException` does occur for XPack test
https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(7.2.x)/AXIS_VARIABLE=0,label_exp=!master/9137/

**Comment by lipusz** [comment]
Hello @xbrianlee 

As I can see `LocalFile.Elasticsearch7EE#XPackSmokeTest` has passed in the test run you've linked above. :thinking: Can you please double check it on Monday?

Thank you!

**Comment by lipusz** [comment]
It'd be nice if we could include this fix in the upcoming ES7 connector release for CCR so we don't need to do a separate release.

**Comment by xbrianlee** [comment]
Sorry typo...that exception doesn't occur. I fixed my comment above.

**Comment by lipusz** [comment]
Thanks, @xbrianlee ! :+1:

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84202

**Pull request closed without merging**
