### PR TITLE
LPS-60670

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by BryanEngler** [comment]
is there a reason that setParallel gets called after all the other setters and right before performActions()? if not then can you SF it to go before setPerformActionMethod()?

**Comment by arbetts** [comment]
I can SF it to place it there ... initially i was thinking that executing the actions in parallel is a special circumstance that should be more visible to the developer... there may be bugs if any state information is included in the perform action method.

if you think it makes more sense to be in line with everything else, then I can SF it.

**Comment by BryanEngler** [comment]
ya we should probably just follow the normal source formatting rules because someone will eventually source format it... if you think its that special of a case then maybe you can add a comment next to the method? i feel like that would make it more visible than just calling the method "out of order".

**Comment by BryanEngler** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/2058

**Pull request closed without merging**
