### PR TITLE
[TS] LPS-90187 All facet buckets need to be checked with a field

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-90187
https://issues.liferay.com/browse/LPP-32946

Hello @BryanEngler,

Your changes worked perfectly, I just squashed commits and am resending it to you.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey @joshuacords 

Can you please update the subject and add the usual content "[TS] LPS-xxxx quick summary".

Thanks!

**Comment by BryanEngler** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/68125

**Pull request closed without merging**
