### PR TITLE
LPS-60830

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by BryanEngler** [comment]
closing because of failed tests

**Comment by BryanEngler** [comment]
my bad, didnt see the new pushed changes...

**Comment by BryanEngler** [comment]
this doesnt feel right. youre changing the api of the interface but only using the parameter in one out of the 20 classes that implements it... lets see if we can keep the fix within wiki without having to change any api

**Pull request closed without merging**
