### PR TITLE
LPS-133224 object entry filtering

### PR DESCRIPTION
**Pull request by BryanEngler**
hey @javierdearcos, thanks for the additional info and for adding some tests. i would like to make the changes to the query "building" logic, instead of the query "translating" logic. i am running tests here, let me know if this works for your needs or if i maybe missed something. thanks!

thinking we might need something like this in NestedFieldQueryHelper?
public Filter getFilter(String field, Function<String, Filter> queryFunction);

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by javierdearcos** [comment]
Hello @BryanEngler,

Thank you very much! This way seems better and makes more sense to put it inside the "building query" logic. Very clean. It is great to learn better ways of achieving what you wanted to do.

About the `getFilter` method in the NestedFieldQueryHelper, I understand that is to return the Filter directly instead of the query, to avoid always creating a QueryFilter. Is correct? In that case, makes sense to me.

There are some cases left (lt, gt, ...) related to RangeTermFilter, but I think it is better to pass the first PR and then I will create new tests and complete these cases.

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
hey @javierdearcos, the point of the getFilter method would actually be to work around the fact that in portal-kernel we dont have an ExistsQuery to replace the ExistsFilter, or a TermsQuery to replace the TermsFilter... but I actually found another way around these issues by using wildcard and boolean queries. I dont think implementing the getFilter method actually would have been possible due to a few other limitations in portal-kernel, but i dont think we need it now.

i did have some WIP for the RangeTermFilter, so i added those changes as well. basically anything that called entityField.getFilterableName(locale) i passed in to _nestedFieldQueryHelper.getQuery()

do you still want to forward this before adding more tests, or do you want to add the tests now since (i think) thats the only thing left to do?

**Comment by BryanEngler** [comment]
looks like i need to update ExpressionVisitorImplTest...

**Comment by javierdearcos** [comment]
> do you still want to forward this before adding more tests, or do you want to add the tests now since (i think) thats the only thing left to do?

I think that it is better to forward this PR and then I will add the tests for the cases that are missing. Just to don't introduce noise

> looks like i need to update ExpressionVisitorImplTest...

Tell me if I can help you with anything

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
didnt notice that ExpressionConvertImplTest was failing as well as ExpressionVisitorImplTest...

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
