### PR TITLE
LPS-59212

### PR DESCRIPTION
**Pull request by arbetts**
this was part of a larger fix that i separated out into its own LPS

### CODE REVIEW

**Comment by BryanEngler** [comment]
did you intentionally leave the suppressWarnings annotation in RolesAdminPortletDataHandler?

**Comment by arbetts** [comment]
no... the IDE added that when i was applying the changes, but i forgot to remove it

**Comment by BryanEngler** [comment]
no worries... just making sure

**Comment by BryanEngler** [comment]
what about applying this to plugins...?

**Comment by arbetts** [comment]
it shouldn't break anything as is because of type erasure in java

i didn't look at the plugin changes because i was already doing a log of manual changes.

**Comment by BryanEngler** [comment]
ya i just wanted to make sure you had thought of it in case bchan or whoever wants those changes as well. in the past i think he has merged the portal commits first so we can see what he says about that and then go from there.

sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/844

**Pull request closed without merging**
