### PR TITLE
LPS-91756 Results ranking frontend dependency and config updates 

### PR DESCRIPTION
**Pull request by thektan**
Updated the dependencies, added tests, and `storybook` which is a frontend development environment to run the frontend components outside of portal context (which allows us to quickly visually test frontend components). I kept the storybook-related files in a single directory: https://github.com/thektan/liferay-portal/tree/123b1e239fc7754d1e45a784d0d7850fcead1b87/modules/apps/portal-search/portal-search-ranking-web/src/main/resources/META-INF/resources/js/stories

Also as a heads up, we'll still need to send more PRs to fix source formatting and make more frontend fixes.

cc: @oliv-yu @wcao20170619

### CODE REVIEW

**Comment by BryanEngler** [comment]
merged

**Comment by ccohick** [comment]
ci:test:bundle

**Comment by BryanEngler** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:reopen

**Pull request closed without merging**
