### PR TITLE
LPS-166987 | LPS-168594 Resolve errors caused by features not supported by solr

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Do we need a similar change in search-experiences-web?

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
@lipusz right now we are going with blacklisting the search experiences modules

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Pull request closed without merging**
