### PR TITLE
LPS-121251 Search result icons

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
ci:test:relevant:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
@lipusz i added some before/after screenshots to the LPS with the changes kevin made. ill wait for your OK before forwarding

**Comment by lipusz** [comment]
Checking out shortly... :popcorn:

**Comment by BryanEngler** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
ci:test:relevant:norebase

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:help

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
