### PR TITLE
LPS-201728 [Components with more than 1 service] LPS-201728 Remove ReindexSingleIndexerBackgroundTaskExecutor from BackgroundTaskConfigurator initialization

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by BryanEngler** [comment]
@rafaprax i think i have figured out the regression this causes

on portal startup im assuming the BackgroundTaskExecutorConfigurator is activating sooner than it previously was, because it no longer has a dependency on ReindexSingleIndexerBackgroundTaskExecutor, and since the ConcurrentReindexManager component is optional (because solr etc doesnt implement/support it), its gets set to null before it has a chance to activate. so when we run a concurrent reindex, we actually dont run an concurrent reindex because the ConcurrentReindexManager is null https://github.com/liferay/liferay-portal/blob/0956ff9eb1b0cee9d28eb9068499d18ee335c782/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/SearchEngineInitializer.java#L101

just a suggestion - i think the first thing i would try to do to resolve this is to just make ReindexPortalBackgroundTaskExecutor a Component(service = BackgroundTaskExecutor.class) as well. let me know if you have any questions, thanks!

**Comment by rafaprax** [comment]
Hey @BryanEngler, thanks for your deep analysis. I'm on it and will take into account your findings.

Thanks so much

**Pull request closed without merging**
