### PR TITLE
LPS-67661

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-67661

The semantic version issue here https://github.com/BryanEngler/liferay-portal/pull/180#issuecomment-241600189 should be fixed now.  I basically did an ant all with all the modified files unstaged.  Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
I removed the system.packages.extra.mf file and did an ant all.  This should hopefully do the trick.

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:retest

**Comment by BryanEngler** [comment]
ci:retest

**Pull request closed without merging**
