### PR TITLE
LPS-104437 

### PR DESCRIPTION
**Pull request by tinatian**
Hi @BryanEngler ,

This a resend of https://github.com/BryanEngler/liferay-portal/pull/462.

Could you please prioritize the review of this? This is a blocker of later sidecar changes.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
hi @tinatia

**Comment by BryanEngler** [comment]
what is the problem you are trying to fix?

**Comment by tinatian** [comment]
@BryanEngler The main problem is to avoid connecting to remote server when current mode is embedded.

Tina.

**Comment by tinatian** [comment]
@BryanEngler I just realized that my pull has a bug, will send you a new pull.

**Pull request closed without merging**
