### PR TITLE
LPS-62886

### PR DESCRIPTION
**Pull request by jgok**

### CODE REVIEW

**Comment by BryanEngler** [comment]
same thing with this one haha... im guessing you didnt add the commit for LRQA-22023?

**Comment by jgok** [comment]
That one looks like it's in master though. https://github.com/liferay/liferay-portal/commit/cd22dee063bbbe4c6dd2df6e04e241f088b127b5

**Comment by BryanEngler** [comment]
test failures look like you forgot to add imports for UserGroupPermissionUtil and PermissionChecker ?

**Comment by jgok** [comment]
ci:retest

**Comment by BryanEngler** [comment]
i also get a build error when trying to compile this fix...

**Comment by BryanEngler** [comment]
im just going to assume that if this fix cant be compiled then it hasnt been tested so im going to close it

**Pull request closed without merging**
