### PR TITLE
[TS] LPS-108052 remove ignored prefilter from solr

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-108052
https://issues.liferay.com/browse/LPP-36209

Tested here: https://github.com/joshuacords/liferay-portal/pull/64/#issuecomment-582728310
Test failure notes here: https://github.com/joshuacords/liferay-portal/pull/64/#issuecomment-582996351

**Problem:** https://issues.liferay.com/browse/LPS-86743 changed Solr's implementation of Low Level Search Engine Adapter API. In particular these [changes](https://github.com/brianchandotcom/liferay-portal/pull/75735/commits/1699da014ed0d208ffcb3288f752f46c0e97878d#diff-283387a568311f2aa49c0f2b10c3d4ecL166-R251) mirrored the Elasticsearch approach. However, they rely on setting a [booleanPrefilter](https://github.com/brianchandotcom/liferay-portal/pull/75735/commits/1699da014ed0d208ffcb3288f752f46c0e97878d#diff-283387a568311f2aa49c0f2b10c3d4ecR239). Unlike [Elasticsearch](https://github.com/liferay/liferay-portal/blob/242542469cc16965c5b86fc19dcaf28649fc9931/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl/src/main/java/com/liferay/portal/search/elasticsearch6/internal/legacy/query/BooleanQueryTranslatorImpl.java#L40-L73), Solr's [translate method ](https://github.com/liferay/liferay-portal/blob/98c9f5f66aeb4fceba67fde613fd529b8c5c0867/modules/apps/portal-search-solr7/portal-search-solr7-impl/src/main/java/com/liferay/portal/search/solr7/internal/query/BooleanQueryTranslatorImpl.java#L36-L55) doesn't consider prefilters. This is because Solr does not handle nested filters. While I initially tried changing the translate method, a change here is impossible because we can't put a filter or a string into the lucene query which must be returned.

**Solution:** After talking with Andre, removing the filter from the deleteEntityDocuments() and flattening the query make the most sense. It removes the prefilter from Solr's implementation. Additionally filter caching on a delete method is unnecessary. The one side effect is the query uses a MUST, SHOULD, SHOULD clause where only a MUST clause is necessary. An example of it looks like this: `{MUST(
	{booleanClauses=[
		{MUST(
			{analyzer=null, className=MatchQuery, cutOffFrequency=null, field=entryClassName, fuzziness=null, fuzzyTranspositions=null, lenient=null, maxExpansions=null, minShouldMatch=null, operator=null, prefixLength=null, slop=null, type=null, value=com.liferay.journal.model.JournalArticle})
		}, 
		{SHOULD(
			{analyzer=null, className=MatchQuery, cutOffFrequency=null, field=entryClassName, fuzziness=null, fuzzyTranspositions=null, lenient=null, maxExpansions=null, minShouldMatch=null, operator=null, prefixLength=null, slop=50, type=PHRASE, value=com.liferay.journal.model.JournalArticle})
		}, 
		{SHOULD(
			{analyzer=null, className=MatchQuery, cutOffFrequency=null, field=entryClassName, fuzziness=null, fuzzyTranspositions=null, lenient=null, maxExpansions=null, minShouldMatch=null, operator=null, prefixLength=null, slop=null, type=PHRASE, value=com.liferay.journal.model.JournalArticle})}
	], className=BooleanQueryImpl})}` 
I don't know of anyway around this behavior or even if it really matters.

Lastly, I fixed the test which broke because `java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.kernel.search.query.FieldQueryFactoryUtil`. The unit test needed to register a FieldQueryFactory which is used inside of the new use of booleanQuery.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search-solr:norebase

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
looks like this breaks at least the SolrIndexWriterExceptionsTest... can you take a look and see if you can tell whether it would be an easy fix or not?

**Comment by joshuacords** [comment]
Looking into it

**Comment by joshuacords** [comment]
Hi @BryanEngler,
The test that broke expected `indexWriter.deleteEntityDocuments(createSearchContext(), null);` to fail because null is passed in for the classname. It now fails differently, throwing a NPE because `public Query addRequiredTerm(String field, String value)` will fail making a query with the null classname. 
Added the fix now.

**Comment by joshuacords** [comment]
ci:test:search-solr:norebase

**Comment by joshuacords** [comment]
Looks like all the tests are good now.

**Comment by BryanEngler** [comment]
running tests at https://github.com/BryanEngler/liferay-portal/pull/478
i made a change to use TermQuery directly instead of going through the query builder. with query builder the query looked like this:
`+(+companyId:192433453345060159 companyId:"192433453345060159"~50 (companyId:"192433453345060159")^2.0) +(+entryClassName:com.liferay.journal.model.JournalArticle entryClassName:"com.liferay.journal.model.JournalArticle"~50 (entryClassName:"com.liferay.journal.model.JournalArticle")^2.0)`
with term queries it looks like this:
`+companyId:985595803129668119 +entryClassName:com.liferay.journal.model.JournalArticle`

**Pull request closed without merging**
