### PR TITLE
LPS-110202 Add minimumShouldMatch to 1 since elasticsearch 7 changed it to 0. (https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_the_filter_context_has_been_removed)

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:search-es7

**Comment by inacionery** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-es7

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
test is still failing for solr

**Pull request closed without merging**
