### PR TITLE
LPS-59018 Sort the list of indexers in the control panel by class name and remove duplicate indexers from the list

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by BryanEngler** [comment]
looks pretty good... im just curious why dont we return an unmodifiableSet in getIndexers?

**Comment by Preston-Crary** [comment]
Because we do not need to. We are already making a copy so any changes that are made to the copy do not effect us (for example sorting).

**Comment by BryanEngler** [comment]
sent to mccann https://github.com/jonathanmccann/liferay-portal/pull/837

**Pull request closed without merging**
